# Generated by Django 2.2.7 on 2019-11-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uesrname', models.CharField(max_length=64, verbose_name='사용자명')),
                ('password', models.CharField(max_length=64, verbose_name='비밀번호')),
                ('registered_datetime', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
            ],
            options={
                'db_table': 'study_1_user',
            },
        ),
    ]
