# Generated by Django 2.2.7 on 2019-11-18 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191118_0923'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='uesrname',
            new_name='username',
        ),
    ]
